"""Add start_date and end_date to classes table

Revision ID: 684a453ecbdb
Revises: 
Create Date: 2025-08-05 18:55:05.196220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684a453ecbdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StartDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('EndDate', sa.Date(), nullable=True))
        
    op.execute("""
            UPDATE classes 
            SET StartDate = CASE 
                WHEN Semester = 'Học kỳ 1' THEN CONCAT(AcademicYear, '-09-01')::DATE
                WHEN Semester = 'Học kỳ 2' THEN CONCAT(SUBSTRING(AcademicYear, 1, 4), '-02-01')::DATE
                ELSE '2024-09-01'::DATE
            END,
            EndDate = CASE 
                WHEN Semester = 'Học kỳ 1' THEN CONCAT(SUBSTRING(AcademicYear, 1, 4), '-12-31')::DATE
                WHEN Semester = 'Học kỳ 2' THEN CONCAT(SUBSTRING(AcademicYear, 6, 4), '-06-30')::DATE
                ELSE '2024-12-31'::DATE
            END
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('EndDate')
        batch_op.drop_column('StartDate')

    # ### end Alembic commands ###
